# Generated by Django 3.1.7 on 2023-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendeaseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='dates_present',
            field=models.JSONField(default=list),
        ),
    ]
