# Generated by Django 3.1.7 on 2023-03-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendeaseapp', '0003_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='password',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
